# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('cmdstag', ['core', 'network'])
    module.source = [
        'model/ipv4-cmds-tag.cc',
        'helper/cmdstag-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('cmdstag')
    module_test.source = [
        'test/cmdstag-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'cmdstag'
    headers.source = [
        'model/ipv4-cmds-tag.h',
        'helper/cmdstag-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

